name: autodeploy
run-name: ${{ github.actor }} is deploying the site
on: [push]
jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
    

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        env:
          MY_EMAIL: stevez9101@gmail.com
          MY_NAME: grififth
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          git remote set-url origin https://$MY_NAME:${{ secrets.GH_SECRET }}@github.com/mchackathon23/mchackathon-site-new.git
          npm ci
          npm run deploy
